# Site settings
title: PawFinder Service API
description: Connecting paws with people

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-paginate
  - jekyll-feed
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

#GitHub Pages settings
url: "https://rhyannonjoy.github.io"
baseurl: "/pawfinder-service"

# Author info (used in sidebar)
author:
  name: Rhyannon Rodriguez
  email: rhyannon.joy@gmail.com

# Add "View on GitHub" button
aux_links:
  "View on GitHub":
    - "https://github.com/rhyannonjoy/pawfinder-service"

# Open aux links in new tab
aux_links_new_tab: true

# Navigation with nested items
nav_items:
  - title: "Home"
    url: "/"
  - title: "Start Here"
    url: "/docs/overview/"
    children:
      - { title: "Overview", url: "/docs/overview/" }
      - { title: "Installation Guide", url: "/docs/overview/installation-guide/" }
      - { title: "Authentication Guide", url: "/docs/overview/authentication-guide/" }
      - { title: "Quickstart Guide", url: "/docs/overview/quickstart-guide/" }
      - { title: "Contribution Guide", url: "/docs/overview/contribution-guide/" }
  - title: "API Reference"
    url: "/docs/api-reference/"
    children:
    - title: "API Index"
      url: "/docs/api-reference/api-index/"
    - title: "/pets"
      children:
        - title: "/pets resource"
          url: "/docs/api-reference/pets-resource/"
        - title: "Get all pet profiles"
          url: "/docs/api-reference/get-all-pets/"
        - title: "Get a pet profile by ID"
          url: "/docs/api-reference/get-pets-by-id/"
        - title: "Get pet profiles using filters"
          url: "/docs/api-reference/get-pets-with-filters/"
        - title: "Get pet profiles from a specific shelter"
          url: "/docs/api-reference/get-pets-from-shelter/"
        - title: "Add a new pet profile"
          url: "/docs/api-reference/post-pets/"
        - title: "Replace a pet profile"
          url: "/docs/api-reference/put-pets-by-id/"
        - title: "Partially update a pet profile"
          url: "/docs/api-reference/patch-pets-by-id/"
        - title: "Delete a pet profile"
          url: "/docs/api-reference/delete-pets-by-id/" 
    - title: "/shelters"
      children:
        - title: "/shelters resource"
          url: "/docs/api-reference/shelters-resource/"
        - title: "Get all shelter profiles"
          url: "/docs/api-reference/get-all-shelters/"
        - title: "Get a shelter profile by ID"
          url: "/docs/api-reference/get-shelters-by-id/"
        - title: "Add a new shelter profile"
          url: "/docs/api-reference/post-shelters/"
        - title: "Replace a shelter profile"
          url: "/docs/api-reference/put-shelters-by-id/"
        - title: "Partially update a shelter profile"
          url: "/docs/api-reference/patch-shelters-by-id/"
        - title: "Delete a shelter profile"
          url: "/docs/api-reference/delete-shelters-by-id/"
  - title: "Tutorials"
    url: "/docs/tutorials/"
    children:
    - title: "API Fundamentals"
      url: "/docs/tutorials/api-fundamentals/"
      children:
        - { title: "Find the perfect pet", url: "/docs/tutorials/api-fundamentals/find-perfect-pet/" }
        - { title: "Mark a pet as adopted", url: "/docs/tutorials/api-fundamentals/mark-pet-adopted/" }
        - { title: "Track adoption status", url: "/docs/tutorials/api-fundamentals/track-adoption-status/" }
    - title: "Building Applications"
      url: "/docs/tutorials/building-applications/"
      children:
        - { title: "Build a location-aware search", url: "/docs/tutorials/building-applications/build-location-aware-search/" }
  - title: "GitHub"
    url: "https://github.com/rhyannonjoy/pawfinder-service"
    external: true
